export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_COLOR = "FILTER_PRODUCTS_BY_COLOR";
export const FILTER_PRODUCTS_BY_BRAND = "FILTER_PRODUCTS_BY_BRAND";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";